// require models folder
const db = require('../mongo_models/index.js')

// hardcoded data for seeding
db.Pokemon.create([
    {
        nickname: 'Pokemon 1',
        image: 'http://placekitten.com/350/350',
        sprite: './public/css/images/wormber-movement.gif',
        level: 3,
        species: 'Caterpie',
        type_1: 'Bug',
        type_2: undefined,
        ability: 'Shield Dust',
        dex_entry: 'dex entry here',
        hit_points: 8,
        defense: 8,
        player: '',
        move_1: 'Tackle',
        move_2: 'String Shot',
        move_3: undefined,
        move_4: undefined,        
    },
    {
        nickname: 'Pokemon 2',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 4,
        species: 'Pidgey',
        type_1: 'Normal',
        type_2: 'Flying',
        ability: 'Keen Eye',
        dex_entry: 'dex entry here',
        hit_points: 9,
        defense: 9,
        player: '',
        move_1: 'Tackle',
        move_2: undefined,
        move_3: undefined,
        move_4: undefined,    
    },
    {
        nickname: 'Pokemon 3',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 5,
        species: 'Pidgey',
        type_1: 'Normal',
        type_2: 'Flying',
        ability: 'Keen Eye',
        dex_entry: 'dex entry here',
        hit_points: 11,
        defense: 11,
        player: '',
        move_1: 'Tackle',
        move_2: 'Sand Attack',
        move_3: undefined,
        move_4: undefined,       
    },
    {
        nickname: 'Pokemon 4',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 4,
        species: 'Rattata',
        type_1: 'Normal',
        type_2: undefined,
        ability: 'Run Away',
        dex_entry: 'dex entry here',
        hit_points: 8,
        defense: 8,
        player: '',
        move_1: 'Tackle',
        move_2: 'Tail Whip',
        move_3: 'Quick Attack',
        move_4: undefined    
    },
    {
        nickname: 'Pokemon 5',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 5,
        species: 'Charmander',
        type_1: 'Fire',
        type_2: undefined,
        ability: 'Blaze',
        dex_entry: 'dex entry here',
        hit_points: 12,
        defense: 12,
        player: '',
        move_1: 'Scratch',
        move_2: 'Growl',
        move_3: undefined,
        move_4: undefined,      
    },
    {
        nickname: 'Pokemon 6',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 6,
        species: 'Spearow',
        type_1: 'Normal',
        type_2: 'Flying',
        ability: 'Keen Eye',
        dex_entry: 'dex entry here',
        hit_points: 10,
        defense: 10,
        player: '',
        move_1: 'Peck',
        move_2: 'Growl',
        move_3: 'Leer',
        move_4: undefined    
    },
    {
        nickname: 'Pokemon 7',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 3,
        species: 'Spearow',
        type_1: 'Normal',
        type_2: 'Flying',
        ability: 'Keen Eye',
        dex_entry: 'dex entry here',
        hit_points: 6,
        defense: 6,
        player: '',
        move_1: 'Peck',
        move_2: 'Growl',
        move_3: undefined,
        move_4: undefined,      
    },
    {
        nickname: 'Pokemon 8',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 5,
        species: 'Squirtle',
        type_1: 'Water',
        type_2: undefined,
        ability: 'Torrent',
        dex_entry: 'dex entry here',
        hit_points: 12,
        defense: 12,
        player: '',
        move_1: 'Tackle',
        move_2: 'Tail Whip',
        move_3: undefined,
        move_4: undefined,       
    },
    {
        nickname: 'Pokemon 9',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 3,
        species: 'Rattata',
        type_1: 'Normal',
        type_2: undefined,
        ability: 'Run Away',
        dex_entry: 'dex entry here',
        hit_points: 7,
        defense: 7,
        player: '',
        move_1: 'Tackle',
        move_2: 'Tail Whip',
        move_3: undefined,
        move_4: undefined,       
    },
    {
        nickname: 'Pokemon 10',
        image: 'http://placekitten.com/350/350',
        sprite: '',
        level: 4,
        species: 'Caterpie',
        type_1: 'Bug',
        type_2: undefined,
        ability: 'Shield Dust',
        dex_entry: 'dex entry here',
        hit_points: 9,
        defense: 9,
        player: '',
        move_1: 'Tackle',
        move_2: 'String Shot',
        move_3: undefined,
        move_4: undefined,    
    }
])
.then(() => {
    console.log('Success!')
    process.exit()
})
.catch(err => {
    console.log('Failure!', err)
    process.exit()
})